"""Agregar campo camera_ip al modelo Robot

Revision ID: 372a16cf82fd
Revises: 520b0ebf8232
Create Date: 2025-11-16 01:03:59.293177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372a16cf82fd'
down_revision = '520b0ebf8232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_ip', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.drop_column('camera_ip')

    # ### end Alembic commands ###
